version: '3'
services:
  db:
    container_name: db
    image: mysql
    restart: on-failure
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: coviddb1
      MYSQL_ROOT_PASSWORD: root
    networks:
      backend:
  app:
    container_name: app
    build: .
    networks:
      backend:
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.jpa.hibernate.ddl-auto=create-drop
      - spring.datasource.url=jdbc:mysql://db:3306/coviddb1
      - spring.datasource.username=root
      - spring.datasource.password=root
    restart: on-failure
networks:
  backend: